### ISSUE TITLE
Get-SPDiagnosticConfig : Cannot access the local farm.

### ISSUE THREAD

**Issue by sbergwall** [brianlala/AutoSPUpdater#1]
Hi,

When installing kb4011593 on a SharePoint Server 2013 i receive the following error afton PSConfig have been run:

_Get-SPDiagnosticConfig : Cannot access the local farm. Verify that the local farm is properly configured, currently
available, and that you have the appropriate permissions to access the database before trying again.
At C:\Program Files\WindowsPowerShell\Modules\AutoSPUpdater\AutoSPUpdaterModule.psm1:415 char:31
     $PSConfigLogLocation = $((Get-SPDiagnosticConfig).LogLocation) -r ...
                               ~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidData: (Microsoft.Share...iagnosticConfig:SPCmdletGetDiagnosticConfig) [Get-SPDiag
   nosticConfig], SPCmdletException
     FullyQualifiedErrorId : Microsoft.SharePoint.PowerShell.SPCmdletGetDiagnosticConfig

 Could not find PSConfig log file!
At C:\Program Files\WindowsPowerShell\Modules\AutoSPUpdater\AutoSPUpdaterModule.psm1:419 char:9
         Throw " - Could not find PSConfig log file!"
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: ( - Could not find PSConfig log file!:String) [], RuntimeException
     FullyQualifiedErrorId :  - Could not find PSConfig log file!_

The update seems to have been installed correctly.

I have had this problem on 3 farms, all single nodes.

Simon

**Comment by brianlala** [comment]
Let me try to reproduce on my own single-server 2013 farm and I'll get back to you. 

There seems to be an issue in SP2016 with the PS console losing its connection to the farm after running PSConfig, but I haven't seen it in 2013 yet.

**Comment by brianlala** [comment]
I've successfully reproduced this. Not an issue with the AutoSPUpdater script though, I'll have to raise it internally to see what's known about it.

Brian

**Comment by brianlala** [comment]
I just tried to repro this again on the same farm with the recently-released January 2018 CU and got no errors. So it may have been a transient issue only present in the December 2017 CU. More testing is required though really.

**Comment by sbergwall** [comment]
Thanks for your response Brian.

Ive tried update with the January 2018 CU also, with no problem. 

Thank you for an awesome function!

**Comment by brianlala** [comment]
Good to hear, cheers!
